name: CasperCar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_chat_bubble: ^2.0.0
  cool_alert: ^1.1.0
  rflutter_alert: ^2.0.4
  google_maps_flutter: ^2.1.6
  flutter_barcode_scanner: 2.0.0
  geolocator: 8.2.1
  geocoding: 2.0.4
<<<<<<< HEAD
  google_fonts: ^3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

=======
  flutter: 
    sdk: flutter
  
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

>>>>>>> 1caba59d7f06a1c39da57048c99e785d6792b819
flutter: 
  assets: 
    - assets/images/caspercar.png
    - assets/images/honda.png
    - assets/images/mercedes.png
    - assets/images/toyota.png
    - assets/images/zainul.jpeg
    - assets/images/abdullah.jpg
    - assets/images/elsa.jpeg
    - assets/images/abdullah.jpeg
    - assets/images/setiawan.jpeg
    - assets/images/bmw.png
    - assets/images/berhasil.png
    - assets/images/gagal.png
  fonts: 
    - family: Montserrat
  uses-material-design: true

